# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Milanothorium"
license = "MIT"
licenselink = "https://github.com/THS-on/milanothorium/blob/master/LICENSE"
description = "Theme for a cooking blog based on NEDEBRUG"
homepage = "https://github.com/THS-on/milanothorium"
tags = ["cooking", "responsive", "blog"]
features = ["responsive", "indexing"]
min_version = 0.34

[author]
  name = "THS-on"
  homepage = "https://github.com/THS-on"

# If porting an existing theme
[original]
  name = "NEDERBURG"
  homepage = "https://github.com/appernetic/hugo-nederburg-theme"
