baseurl = "http://example.com"
title = "Milanothorium"
theme = "milanothorium"
languageCode = "en"
DefaultContentLanguage = "en"
googleAnalytics = ""
paginate = 5 #frontpage pagination

[params]
  slogan = "Cooking blog"
  description = "Describe your website" # meta description
  copyright = [
    "&copy; 2018 YOURNAME",
    "Based on Nederburg Hugo Theme by [Appernetic](https://appernetic.io)."
    ]

[languages]
  [languages.en]
    weight = 1
    languageName = 1
    [[languages.en.menu.main]]
      identifier = "home-en"
      name       = "Home"
      url        = "/"
      weight     = 1

    [[languages.en.menu.main]]
      identifier = "recipes-en"
      name       = "Recipes"
      url        = "recipes/"
      weight     = 2

    [[languages.en.menu.main]]
      identifier = "overview-recipes-en" #Hugo doesn't like if we have the same name twice, so we add an identifier
      name       = "Overview"
      parent     = "recipes-en"
      url        = "/recipes/overview"
      weight     = 1

    [[languages.en.menu.main]]
      identifier = "ingredients-en"
      name       = "Ingredients"
      url        = "ingredients/"
      weight     = 3

    [[languages.en.menu.main]]
      identifier = "overview-ingredients-en"
      name       = "Overview"
      url        = "/ingredients/overview"
      parent     = "ingredients-en"
      weight     = 1

    [languages.en.taxonomies]
      category = "categories"
      tag      = "tags"
    [languages.en.permalinks]
        ingredients = "/ingredients/:slug/"
        recipes = "/recipes/:slug/"
        about = "/:slug/"
        post = "/post/:slug"
[params.social]
  email         = "test@example.com"
  rss           = true
