baseurl = "http://example.com"
title = "Milanothorium"
theme = "milanothorium"
languageCode = "en"
DefaultContentLanguage = "en"
disableLanguages = ["de"] #Disable German langauge 
googleAnalytics = ""
paginate = 5 #frontpage pagination

[params]
  slogan = "Cooking blog"
  description = "Describe your website" # meta description
  copyright = [
    "&copy; 2018 YOURNAME",
    "Based on Nederburg Hugo Theme by [Appernetic](https://appernetic.io)."
    ]

[languages]
  [languages.de]
    baseurl="http://example.com"
    weight = 2
    languageName = "Deutsch"
    [[languages.de.menu.main]]
      identifier = "home"
      name       = "Home"
      url        = "/"
      weight     = 1

    [[languages.de.menu.main]]
      identifier = "recipes"
      name       = "Rezepte"
      url        = "rezepte/"
      weight     = 2

    [[languages.de.menu.main]]
      identifier = "overview-recipes" #Hugo doesn't like if we have the same name twice, so we add an identifier
      name       = "Übersicht"
      parent     = "recipes"
      url        = "/rezepte/uebersicht"
      weight     = 1

    [[languages.de.menu.main]]
      identifier = "ingredients"
      name       = "Zutaten"
      url        = "zutaten/"
      weight     = 3

    [[languages.de.menu.main]]
      identifier = "overview-ingredients"
      name       = "Übersicht"
      url        = "/zutaten/uebersicht"
      parent     = "ingredients"
      weight     = 1
    [languages.de.taxonomies]
      category = "kategorien"
      tag = "tags"
    [languages.de.permalinks]
      ingredients = "/zutaten/:slug/"
      recipes = "/rezepte/:slug/"
      post = "/post/:slug"
      about = "/:slug/"
  [languages.en]
    baseurl="http://example.com"
    weight = 1
    languageName = 1
    title = "Title"
    [[languages.en.menu.main]]
      identifier = "home-en"
      name       = "Home"
      url        = "/"
      weight     = 1

    [[languages.en.menu.main]]
      identifier = "recipes-en"
      name       = "Recipes"
      url        = "recipes/"
      weight     = 2

    [[languages.en.menu.main]]
      identifier = "overview-recipes-en" #Hugo doesn't like if we have the same name twice, so we add an identifier
      name       = "Overview"
      parent     = "recipes-en"
      url        = "/recipes/overview"
      weight     = 1

    [[languages.en.menu.main]]
      identifier = "ingredients-en"
      name       = "Ingredients"
      url        = "ingredients/"
      weight     = 3

    [[languages.en.menu.main]]
      identifier = "overview-ingredients-en"
      name       = "Overview"
      url        = "/ingredients/overview"
      parent     = "ingredients-en"
      weight     = 1

    [languages.en.taxonomies]
      category = "categories"
      tag      = "tags"
    [languages.en.permalinks]
        ingredients = "/ingredients/:slug/"
        recipes = "/recipes/:slug/"
        about = "/:slug/"
        post = "/post/:slug"
    [languages.en.params]
        slogan = "Your own slogan"


[params.social]
  email         = "test@example.com"
  rss           = true
